# Generated by Django 5.2.12 on 2026-03-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('secretariate', 'Secretariate'), ('content_manager', 'Content Manager'), ('user', 'User'), ('swg', 'SWG')], default='user', max_length=20),
        ),
    ]
