services:
  web:
    build: .
    command: gunicorn hta.wsgi:application --bind 0.0.0.0:8000 --workers 3 --reload
    volumes:
      - .:/app
      - media_volume:/app/media
      - logs_volume:/app/logs
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  celery:
    build: .
    entrypoint: []
    command: celery -A hta worker -l info -Q proposals,files,emails,celery
    volumes:
      - .:/app
      - logs_volume:/app/logs
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  media_volume:
  logs_volume:
  redis_data:
