"""
Django settings for hta project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
import os
from pathlib import Path

from django.conf import settings
import json



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
os.makedirs(os.path.join(BASE_DIR, 'logs'), exist_ok=True)

# Secret Key
SECRET_KEY = '83d29a715b21a101f7860ca9c8904b0465edd9fb2c5b2eef2e4f74953920166b'

# Debug mode
# DEBUG = False
DEBUG = True  # Set to False in production

# Allowed Hosts
ALLOWED_HOSTS = ['bptap.health.go.ke','localhost','127.0.0.1']
# ALLOWED_HOSTS = ['*']  # For development only, allows all hosts. Change in production!

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'rest_framework',
    'rest_framework_simplejwt',
    # 'rest_framework_simplejwt.token_blacklist',  
    
    'users',
   # 'users.apps.UsersConfig',
    'members',
    'corsheaders',
    
    # 
    'channels',
    'channels_redis',
    #  audit log
    'auditlog',
    'django_crontab', # added  new
    
    
]

# cronjobs added new
CRONJOBS = [
    # Every 3 minutes
    ('*/3 * * * *', 'users.cron.send_email_job.send_email_cron'),
]

# Channel Layers configuration
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hta.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hta.wsgi.application'

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10000000,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
            'rest_framework_simplejwt.authentication.JWTAuthentication',
        ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated', 
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}

CORS_ALLOWED_ORIGINS = [
    "https://bptap.health.go.ke",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
CSRF_TRUSTED_ORIGINS = [
    "https://bptap.health.go.ke",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
     'default': {
         'ENGINE': 'django.db.backends.sqlite3',
         'NAME': BASE_DIR / 'db.sqlite3',
     }
}


#DATABASES = {
#    'default': {
#       'ENGINE': 'django.db.backends.postgresql',
#       'NAME': '*****',
#       'USER': '****',
#        'PASSWORD': '*******',
#        'HOST': 'localhost',
#        'PORT': 5432,
#    }
#}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True



AUTH_USER_MODEL = 'users.CustomUser'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = 'static/'

# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_URL = '/media/'
# MEDIA_URL = 'https://bptap.health.go.ke/media/'
# MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
#REACT_APP_DIR = os.path.join(BASE_DIR, 'frontend')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#  jwt settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=2),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=10),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    
    'JTI_CLAIM': 'jti',
    
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=120),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=7),

    'USER_CLAIMS': lambda user: {
        'role': user.role,
        'email': user.email
    },
}


# # ASGI Application
# ASGI_APPLICATION = 'hta.asgi.application'



# Celery Configs
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Africa/Nairobi'

# routing for different queues. and tasks
CELERY_TASK_ROUTES = {
    'users.tasks.process_proposal_submission': {'queue': 'proposals'},
    'users.tasks.process_file_upload': {'queue': 'files'},
    'users.tasks.send_confirmation_email': {'queue': 'emails'},
}

# Worker configuration
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000



#  email config
config_path = BASE_DIR / "config.json"
# print()
with open(config_path) as config_file:
    config = json.load(config_file)
    
EMAIL_BACKEND = config.get('EMAIL_BACKEND')
EMAIL_HOST = config.get('EMAIL_HOST')
EMAIL_PORT = int(config.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = config.get('EMAIL_USE_TLS', True)
EMAIL_HOST_USER = config.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = config.get('DEFAULT_FROM_EMAIL')
SUPPORT_EMAIL = config.get('SUPPORT_EMAIL')
FRONTEND_URL = config.get('FRONTEND_URL')

    

#logging - added cronjob logger
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },

    # ────────────────────── HANDLERS ───────────────────────
    'handlers': {
        'django_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(settings.BASE_DIR, 'logs', 'django.log'),
            'formatter': 'verbose',
        },

        #cron log
        'email_cron_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(settings.BASE_DIR, 'logs', 'django_email_cron.log'),
            'formatter': 'verbose',
        },

        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },

    # ────────────────────── LOGGERS ────────────────────────
    'loggers': {
        'users.tasks': {
            'handlers': ['django_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'celery': {
            'handlers': ['django_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },

        #  Cron logger -------------------------------------------------
        'users.cron.send_email_job': {
            'handlers': ['email_cron_file', 'console'],  
            'level': 'INFO',
            'propagate': False,
        },
    },


    'root': {
        'handlers': ['django_file', 'console'],
        'level': 'INFO',
    },
}