# Generated by Django 5.2.12 on 2026-03-13 10:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionTool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criteria', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('scoring_mechanism', models.TextField(blank=True, null=True)),
                ('scores', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CriteriaInformation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brief_info', models.TextField(blank=True, null=True)),
                ('clinical_effectiveness', models.TextField(blank=True, null=True)),
                ('burden_of_disease', models.TextField(blank=True, null=True)),
                ('bod_type', models.CharField(blank=True, choices=[('DALY', 'DALY'), ('QALY', 'QALY'), ('PREVALENCE', 'Prevalence'), ('INCIDENCE', 'Incidence')], max_length=20, null=True)),
                ('population', models.TextField(blank=True, null=True)),
                ('equity', models.TextField(blank=True, null=True)),
                ('cost_effectiveness', models.TextField(blank=True, null=True)),
                ('budget_impact_affordability', models.TextField(blank=True, null=True)),
                ('feasibility_of_implementation', models.TextField(blank=True, null=True)),
                ('catastrophic_health_expenditure', models.TextField(blank=True, null=True)),
                ('access_to_healthcare', models.TextField(blank=True, null=True)),
                ('congruence_with_health_priorities', models.TextField(blank=True, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria_information', to='users.interventionproposal')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['intervention'], name='idx_criteria_intervention')],
            },
        ),
        migrations.CreateModel(
            name='InterventionScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.JSONField(blank=True, default=dict)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='users.interventionproposal')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.selectiontool')),
            ],
            options={
                'unique_together': {('reviewer', 'intervention', 'criteria')},
            },
        ),
        migrations.CreateModel(
            name='InterventionSystemCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_categories', to='users.interventionproposal')),
                ('system_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interventions', to='app.systemcategory')),
            ],
            options={
                'unique_together': {('intervention', 'system_category')},
            },
        ),
    ]
