# Generated by Django 5.2.12 on 2026-03-13 10:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThematicArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color_code', models.CharField(default='#007bff', help_text='Hex color code for UI', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('description', models.TextField(blank=True, null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_channels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('moderator', 'Moderator'), ('member', 'Member')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='members.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='members',
            field=models.ManyToManyField(related_name='channels', through='members.ChannelMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DecisionRationale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(max_length=20)),
                ('detailed_rationale', models.TextField(blank=True, help_text='Detailed explanation', null=True)),
                ('approval_conditions', models.TextField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_type', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='EventDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='events/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='members.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='events/images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='members.event')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.TextField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(help_text='Feedback message')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=100, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('admin_response', models.TextField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImplementationTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('implementation_start_date', models.DateField(blank=True, help_text='When implementation actually started', null=True)),
                ('expected_completion_date', models.DateField(blank=True, help_text='Expected completion date', null=True)),
                ('actual_completion_date', models.DateField(blank=True, help_text='When implementation was completed', null=True)),
                ('progress_percentage', models.IntegerField(default=0, help_text='Overall implementation progress (0-100%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('current_status', models.TextField(blank=True, help_text='Current implementation status description')),
                ('key_activities_completed', models.TextField(blank=True, help_text='Description of key activities completed')),
                ('implementation_notes', models.TextField(blank=True, help_text='Detailed notes about implementation progress')),
                ('is_completed', models.BooleanField(default=False, help_text='Mark as true when implementation is complete')),
                ('completion_remarks', models.TextField(blank=True, help_text='Final remarks upon completion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_implementations', to=settings.AUTH_USER_MODEL)),
                ('decision_rationale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='implementation', to='members.decisionrationale')),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_implementations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Implementation Tracking',
                'verbose_name_plural': 'Implementation Trackings',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='members.channel')),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='members.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('description', models.TextField(blank=True, null=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('allow_multiple_choices', models.BooleanField(default=False)),
                ('allow_comments', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='members.channel')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_polls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PollComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_comments', to='members.poll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='members.poll')),
            ],
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='members.polloption')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='members.poll')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poll_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('review_stage', models.CharField(choices=[('initial', 'Initial'), ('under_review', 'Under Review'), ('needs_revision', 'Needs Revision'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='initial', max_length=20)),
                ('priority_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], max_length=20, null=True)),
                ('implementation_status', models.CharField(blank=True, choices=[('not_started', 'Not Started'), ('planning', 'Planning'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(help_text='Notes on the task')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracker', to='users.interventionproposal')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='decisionrationale',
            name='tracker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision_rationale', to='members.proposaltracker'),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('type', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('documents', models.FileField(blank=True, null=True, upload_to='records/documents/')),
                ('images', models.ImageField(blank=True, null=True, upload_to='records/images/')),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('type', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('documents', models.FileField(blank=True, null=True, upload_to='resources/documents/')),
                ('images', models.ImageField(blank=True, null=True, upload_to='resources/images/')),
                ('link', models.URLField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('complainant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('complainant_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('comment_type', models.CharField(blank=True, max_length=20, null=True)),
                ('content', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='members.proposaltracker')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Notes on the task status', null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('progress', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('complete_date', models.DateField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.proposaltracker')),
            ],
        ),
        migrations.AddField(
            model_name='proposaltracker',
            name='assigned_reviewers',
            field=models.ManyToManyField(blank=True, related_name='assigned_proposals', through='members.ReviewerAssignment', through_fields=('tracker', 'reviewer'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes for the task', null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('review', 'Under Review'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('progress', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('position_x', models.IntegerField(default=0, help_text='Horizontal position in the board')),
                ('position_y', models.IntegerField(default=0, help_text='Vertical position in the board')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position_y', 'position_x', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Assignment-specific notes', null=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='members.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks', through='members.TaskAssignment', through_fields=('task', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposaltracker',
            name='thematic_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.thematicarea'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('content', models.TextField()),
                ('type', models.TextField(blank=True, null=True)),
                ('priority', models.TextField(blank=True, null=True)),
                ('documents', models.FileField(blank=True, null=True, upload_to='announcements/documents/')),
                ('images', models.ImageField(blank=True, null=True, upload_to='announcements/images/')),
                ('link', models.URLField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='members_ann_created_106603_idx'), models.Index(fields=['created_by'], name='members_ann_created_7c0dce_idx'), models.Index(fields=['is_public'], name='members_ann_is_publ_095c65_idx'), models.Index(fields=['is_pinned'], name='members_ann_is_pinn_22968b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='channelmembership',
            index=models.Index(fields=['channel', 'user'], name='members_cha_channel_23ec4e_idx'),
        ),
        migrations.AddIndex(
            model_name='channelmembership',
            index=models.Index(fields=['role'], name='members_cha_role_1e1981_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='channelmembership',
            unique_together={('channel', 'user')},
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['name', 'is_private'], name='members_cha_name_5f2216_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['created_at'], name='members_cha_created_43da34_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_date', 'event_type'], name='members_eve_start_d_43003f_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['-created_at'], name='members_eve_created_497c29_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['-created_at'], name='members_fee_created_b51e0f_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['status'], name='members_fee_status_46b915_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['channel', 'created_at'], name='members_mes_channel_0e0514_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['user'], name='members_mes_user_id_2b0477_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['parent_message'], name='members_mes_parent__325862_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['channel', 'created_at'], name='members_pol_channel_7c3984_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['created_by'], name='members_pol_created_dccf06_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['expires_at'], name='members_pol_expires_5a183f_idx'),
        ),
        migrations.AddIndex(
            model_name='pollcomment',
            index=models.Index(fields=['poll', 'created_at'], name='members_pol_poll_id_993066_idx'),
        ),
        migrations.AddIndex(
            model_name='pollcomment',
            index=models.Index(fields=['user'], name='members_pol_user_id_16c4c2_idx'),
        ),
        migrations.AddIndex(
            model_name='polloption',
            index=models.Index(fields=['poll'], name='members_pol_poll_id_65cc39_idx'),
        ),
        migrations.AddIndex(
            model_name='pollvote',
            index=models.Index(fields=['poll', 'user'], name='members_pol_poll_id_5ce764_idx'),
        ),
        migrations.AddIndex(
            model_name='pollvote',
            index=models.Index(fields=['option'], name='members_pol_option__fa26b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pollvote',
            unique_together={('poll', 'user', 'option')},
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['created_at'], name='members_rec_created_cc1501_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['created_by'], name='members_rec_created_f7758b_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['created_at'], name='members_res_created_d4950d_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['created_by'], name='members_res_created_d0063b_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['is_public'], name='members_res_is_publ_e406d9_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['type'], name='members_res_type_2491a9_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['reference_number'], name='members_res_referen_b9bcb3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewerassignment',
            unique_together={('tracker', 'reviewer')},
        ),
        migrations.AlterUniqueTogether(
            name='taskassignment',
            unique_together={('task', 'user')},
        ),
    ]
