# Generated by Django 6.0.3 on 2026-03-05 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channelmembership',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='members.channel'),
        ),
        migrations.AddField(
            model_name='channelmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channel',
            name='members',
            field=models.ManyToManyField(related_name='channels', through='members.ChannelMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decisionrationale',
            name='decided_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventdocument',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='members.event'),
        ),
        migrations.AddField(
            model_name='eventimage',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='members.event'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='implementationtracking',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_implementations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='implementationtracking',
            name='decision_rationale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='implementation', to='members.decisionrationale'),
        ),
        migrations.AddField(
            model_name='implementationtracking',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_implementations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='members.channel'),
        ),
        migrations.AddField(
            model_name='message',
            name='parent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='members.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poll',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='members.channel'),
        ),
        migrations.AddField(
            model_name='poll',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_polls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pollcomment',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_comments', to='members.poll'),
        ),
        migrations.AddField(
            model_name='pollcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='polloption',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='members.poll'),
        ),
        migrations.AddField(
            model_name='pollvote',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='members.polloption'),
        ),
        migrations.AddField(
            model_name='pollvote',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='members.poll'),
        ),
        migrations.AddField(
            model_name='pollvote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poll_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposaltracker',
            name='proposal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracker', to='users.interventionproposal'),
        ),
        migrations.AddField(
            model_name='decisionrationale',
            name='tracker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision_rationale', to='members.proposaltracker'),
        ),
        migrations.AddField(
            model_name='record',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resource',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='members.proposaltracker'),
        ),
        migrations.AddField(
            model_name='reviewerassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer_assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewerassignment',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewerassignment',
            name='tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.proposaltracker'),
        ),
        migrations.AddField(
            model_name='proposaltracker',
            name='assigned_reviewers',
            field=models.ManyToManyField(blank=True, related_name='assigned_proposals', through='members.ReviewerAssignment', through_fields=('tracker', 'reviewer'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='members.task'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks', through='members.TaskAssignment', through_fields=('task', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposaltracker',
            name='thematic_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.thematicarea'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['created_at'], name='members_ann_created_106603_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['created_by'], name='members_ann_created_7c0dce_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_public'], name='members_ann_is_publ_095c65_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_pinned'], name='members_ann_is_pinn_22968b_idx'),
        ),
        migrations.AddIndex(
            model_name='channelmembership',
            index=models.Index(fields=['channel', 'user'], name='members_cha_channel_23ec4e_idx'),
        ),
        migrations.AddIndex(
            model_name='channelmembership',
            index=models.Index(fields=['role'], name='members_cha_role_1e1981_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='channelmembership',
            unique_together={('channel', 'user')},
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['name', 'is_private'], name='members_cha_name_5f2216_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['created_at'], name='members_cha_created_43da34_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_date', 'event_type'], name='members_eve_start_d_43003f_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['-created_at'], name='members_eve_created_497c29_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['-created_at'], name='members_fee_created_b51e0f_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['status'], name='members_fee_status_46b915_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['channel', 'created_at'], name='members_mes_channel_0e0514_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['user'], name='members_mes_user_id_2b0477_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['parent_message'], name='members_mes_parent__325862_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['channel', 'created_at'], name='members_pol_channel_7c3984_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['created_by'], name='members_pol_created_dccf06_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['expires_at'], name='members_pol_expires_5a183f_idx'),
        ),
        migrations.AddIndex(
            model_name='pollcomment',
            index=models.Index(fields=['poll', 'created_at'], name='members_pol_poll_id_993066_idx'),
        ),
        migrations.AddIndex(
            model_name='pollcomment',
            index=models.Index(fields=['user'], name='members_pol_user_id_16c4c2_idx'),
        ),
        migrations.AddIndex(
            model_name='polloption',
            index=models.Index(fields=['poll'], name='members_pol_poll_id_65cc39_idx'),
        ),
        migrations.AddIndex(
            model_name='pollvote',
            index=models.Index(fields=['poll', 'user'], name='members_pol_poll_id_5ce764_idx'),
        ),
        migrations.AddIndex(
            model_name='pollvote',
            index=models.Index(fields=['option'], name='members_pol_option__fa26b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pollvote',
            unique_together={('poll', 'user', 'option')},
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['created_at'], name='members_rec_created_cc1501_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['created_by'], name='members_rec_created_f7758b_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['created_at'], name='members_res_created_d4950d_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['created_by'], name='members_res_created_d0063b_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['is_public'], name='members_res_is_publ_e406d9_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['type'], name='members_res_type_2491a9_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['reference_number'], name='members_res_referen_b9bcb3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewerassignment',
            unique_together={('tracker', 'reviewer')},
        ),
        migrations.AlterUniqueTogether(
            name='taskassignment',
            unique_together={('task', 'user')},
        ),
    ]
